# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: ark-clusterinfo.spec

# add or remove files that should be synced
files_to_sync:
  - ark-clusterinfo.spec
  - .packit.yaml
  - Makefile

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: ark-clusterinfo
# downstream (Fedora) RPM package name
downstream_package_name: ark-clusterinfo

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-40-x86_64

  - job: copr_build
    trigger: commit
    branch: main
    owner: "led0nk"
    project: ark-clusterinfo
    targets:
      - fedora-40-x86_64
